---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: nats
spec:
  clusterSelector:
    matchLabels:
      projectsveltos.io/role: management
  helmCharts:
  - chartName: nats/nats
    chartVersion: 1.3.9
    helmChartAction: Install
    releaseName: nats
    releaseNamespace: nats
    repositoryName: nats
    repositoryURL: https://nats-io.github.io/k8s/helm/charts/
    values: |-
      config:
        client_advertise: "nats://nats.nats.svc.cluster.local:4222"
        cluster:
          enabled: true
          replicas: 3
        jetstream:
          enabled: true
          fileStore:
            pvc:
              size: 10Gi
        merge:
          accounts:
            SYS:
              users:
                - user: sys
                  pass: sysuser
            clusterOps:
              jetstream: enabled
              default_permissions:
                publish:
                  allow: ">"
                subscribe:
                  allow: ">"
              users:
                - user: sveltos
                  pass: projectsveltos
                - user: repo
                  pass: creator
                - user: admin
                  pass: admin
          system_account: SYS
      service:
        merge:
          spec:
            type: LoadBalancer
            publishNotReadyAddresses: true
            ports:
              - name: nats
                port: 4222
                targetPort: 4222
  syncMode: Continuous