name: Build and Push Multi-Arch Docker Image to GHCR

on:
  push:
    branches: [ main ]
    paths:
      - repo-creator/**
      - .github/workflows/docker-build.yml

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: echo "IMAGE=ghcr.io/${{ github.repository_owner }}/repo-creator" >> $GITHUB_ENV

      - name: Build and push multi-arch image
        uses: docker/build-push-action@v5
        with:
          context: ./repo-creator
          push: true
          tags: ${{ env.IMAGE }}
          platforms: linux/amd64,linux/arm64
